import type { CrisisRegion } from "@/lib/types";

/**
 * Safety layer.
 *
 * Three rules hold everywhere in this app:
 *  1. Every piece of user-written text passes through `screenText` BEFORE it
 *     reaches a model, and the result travels with the response.
 *  2. Crisis resources are rendered by the app, never generated by a model.
 *     A model can time out, drift, or be rate-limited; a component cannot.
 *  3. Resources are region-aware, emergency number first. Someone in crisis in
 *     Melbourne should not have to read past two foreign numbers to reach
 *     Lifeline.
 */

const CRISIS_PATTERNS: RegExp[] = [
  /\bsuicid(e|al)\b/i,
  /\bkill(ing)? my ?self\b/i,
  /\bend(ing)? (my life|it all)\b/i,
  /\btake my own life\b/i,
  /\bself[- ]harm\b/i,
  /\bhurt(ing)? my ?self\b/i,
  /\bcut(ting)? my ?self\b/i,
  /\bdon'?t want to (live|be here|wake up)\b/i,
  /\bwant to die\b/i,
  /\bbetter off (without me|dead)\b/i,
  /\boverdos(e|ing)\b/i,
  /\bno reason to (live|go on)\b/i,
  /\bplan(ning)? to (die|end it)\b/i,
];

const ABUSE_PATTERNS: RegExp[] = [
  /\b(he|she|they) (hits|hit|beats|beat|hurts|hurt) me\b/i,
  /\bafraid to go home\b/i,
  /\bnot safe at home\b/i,
  /\bthreatened to (kill|hurt) me\b/i,
];

const MEDICAL_PATTERNS: RegExp[] = [
  /\bchest pain\b/i,
  /\bcan'?t breathe\b/i,
  /\bstruggling to breathe\b/i,
  /\bshortness of breath\b/i,
  /\bpassing out\b/i,
  /\bfainted\b/i,
  /\bseizure\b/i,
  /\bconvulsion\b/i,
  /\bblue lips\b/i,
  /\bunresponsive\b/i,
  /\bvomiting blood\b/i,
  /\bcoughing up blood\b/i,
  /\bsevere bleeding\b/i,
  /\bnumbness on one side\b/i,
  /\bface is drooping\b/i,
  /\bslurred speech\b/i,
];

const PANIC_PATTERNS: RegExp[] = [
  /\bpanic attack\b/i,
  /\b(i'?m|i am) panicking\b/i,
  /\bheart is racing\b/i,
  /\bchest feels tight\b/i,
  /\bfreaking out\b/i,
  /\bspiral(l)?ing\b/i,
  /\bhyperventilat/i,
];

export type SafetyLevel = "none" | "panic" | "medical" | "crisis";

export type SafetyScreen = {
  level: SafetyLevel;
  /** True when the app must show resources and skip AI interpretation. */
  blocksAi: boolean;
  matched: string[];
};

const matches = (text: string, patterns: RegExp[]) => patterns.some((p) => p.test(text));

/**
 * Highest severity wins. Crisis and medical both block AI interpretation —
 * someone describing chest pain needs an ambulance, not a reframe.
 */
export function screenText(text: string): SafetyScreen {
  const matched: string[] = [];
  if (matches(text, CRISIS_PATTERNS)) matched.push("crisis");
  if (matches(text, ABUSE_PATTERNS)) matched.push("safety-at-home");
  if (matches(text, MEDICAL_PATTERNS)) matched.push("medical");
  if (matches(text, PANIC_PATTERNS)) matched.push("panic");

  if (matched.includes("crisis") || matched.includes("safety-at-home")) {
    return { level: "crisis", blocksAi: true, matched };
  }
  if (matched.includes("medical")) return { level: "medical", blocksAi: true, matched };
  if (matched.includes("panic")) return { level: "panic", blocksAi: false, matched };
  return { level: "none", blocksAi: false, matched };
}

/* ------------------------------------------------------------- resources */

export type CrisisLine = { name: string; contact: string; note?: string; emergency?: boolean };
export type CrisisResources = { region: CrisisRegion; label: string; lines: CrisisLine[] };

const RESOURCES: Record<CrisisRegion, CrisisResources> = {
  AU: {
    region: "AU",
    label: "Australia",
    lines: [
      { name: "Emergency", contact: "000", note: "If you are in immediate danger", emergency: true },
      { name: "Lifeline", contact: "13 11 14", note: "24/7 crisis support" },
      { name: "Beyond Blue", contact: "1300 22 4636" },
      { name: "13YARN", contact: "13 92 76", note: "For Aboriginal and Torres Strait Islander people" },
      { name: "1800RESPECT", contact: "1800 737 732", note: "Family and sexual violence" },
    ],
  },
  NZ: {
    region: "NZ",
    label: "New Zealand",
    lines: [
      { name: "Emergency", contact: "111", emergency: true },
      { name: "Need to talk?", contact: "Call or text 1737", note: "Free, 24/7" },
      { name: "Lifeline Aotearoa", contact: "0800 543 354" },
    ],
  },
  US: {
    region: "US",
    label: "United States",
    lines: [
      { name: "Emergency", contact: "911", emergency: true },
      { name: "Suicide & Crisis Lifeline", contact: "988", note: "Call or text, 24/7" },
      { name: "Crisis Text Line", contact: "Text HOME to 741741" },
    ],
  },
  CA: {
    region: "CA",
    label: "Canada",
    lines: [
      { name: "Emergency", contact: "911", emergency: true },
      { name: "Suicide Crisis Helpline", contact: "988", note: "Call or text, 24/7" },
      { name: "Talk Suicide Canada", contact: "1-833-456-4566" },
    ],
  },
  UK: {
    region: "UK",
    label: "United Kingdom",
    lines: [
      { name: "Emergency", contact: "999", emergency: true },
      { name: "Samaritans", contact: "116 123", note: "Free, 24/7" },
      { name: "Shout", contact: "Text SHOUT to 85258" },
    ],
  },
  IE: {
    region: "IE",
    label: "Ireland",
    lines: [
      { name: "Emergency", contact: "112 or 999", emergency: true },
      { name: "Samaritans", contact: "116 123", note: "Free, 24/7" },
      { name: "Text About It", contact: "Text HELLO to 50808" },
    ],
  },
  INTL: {
    region: "INTL",
    label: "International",
    lines: [
      { name: "Emergency", contact: "Your local emergency number", emergency: true },
      {
        name: "Find a helpline",
        contact: "findahelpline.com",
        note: "Verified crisis lines in over 130 countries",
      },
    ],
  },
};

export const ALL_REGIONS: CrisisRegion[] = ["AU", "NZ", "US", "CA", "UK", "IE", "INTL"];

export function crisisResources(region: CrisisRegion = "AU"): CrisisResources {
  return RESOURCES[region] ?? RESOURCES.INTL;
}

export function regionLabel(region: CrisisRegion): string {
  return (RESOURCES[region] ?? RESOURCES.INTL).label;
}

/**
 * Best-effort region from the browser's IANA timezone, so the right numbers
 * show without asking. Deliberately conservative: anything unrecognised falls
 * through to the international list rather than guessing at an emergency
 * number that would not connect.
 */
export function regionFromTimeZone(timeZone: string | undefined | null): CrisisRegion {
  if (!timeZone) return "INTL";
  const zone = timeZone.toLowerCase();

  if (zone.startsWith("australia/") || zone === "antarctica/macquarie") return "AU";
  if (zone === "pacific/auckland" || zone === "pacific/chatham") return "NZ";
  if (zone === "europe/london" || zone === "europe/belfast") return "UK";
  if (zone === "europe/dublin") return "IE";

  const CANADA = [
    "america/toronto", "america/vancouver", "america/edmonton", "america/winnipeg",
    "america/halifax", "america/st_johns", "america/regina", "america/moncton",
    "america/whitehorse", "america/yellowknife", "america/iqaluit",
  ];
  if (CANADA.includes(zone)) return "CA";

  if (zone.startsWith("america/") || zone.startsWith("us/") || zone === "pacific/honolulu") {
    return "US";
  }
  return "INTL";
}

export const NON_CLINICAL_DISCLAIMER =
  "Mentara is a self-guided wellbeing tool. It is not therapy, not a clinician, and it cannot diagnose or treat anything. If something feels beyond what a tool should hold, please involve a real person.";
