import type { CrisisRegion } from "@/lib/types";

/**
 * Safety layer.
 *
 * Four rules hold everywhere in this app:
 *  1. Every piece of user-written text passes through `screenText` BEFORE it
 *     reaches a model, and the result travels with the response.
 *  2. Crisis resources are rendered by the app, never generated by a model.
 *     A model can time out, drift, or be rate-limited; a component cannot.
 *  3. Resources are region-aware, emergency number first. Someone in crisis in
 *     Melbourne should not have to read past two foreign numbers to reach
 *     Lifeline.
 *  4. Screening runs against EVERY language at once, never just the one the
 *     interface happens to be set to. People in distress write in whichever
 *     language the feeling arrives in — often their first, whatever the app is
 *     showing. Gating the screen on the selected locale would mean the net has
 *     a hole in it for exactly the person most likely to fall through.
 */

/* ------------------------------------------------------------- patterns
 *
 * A note on word boundaries: `\b` is defined around ASCII word characters, so
 * it does not work for Chinese (no spaces between words) or reliably for
 * Arabic. Those languages use plain substring matching instead, which is
 * slightly broader and errs toward catching too much — the right direction to
 * err in.
 */

const CRISIS_PATTERNS: RegExp[] = [
  // English
  /\bsuicid(e|al)\b/i,
  /\bkill(ing)? my ?self\b/i,
  /\bend(ing)? (my life|it all)\b/i,
  /\btake my own life\b/i,
  /\bself[- ]harm\b/i,
  /\bhurt(ing)? my ?self\b/i,
  /\bcut(ting)? my ?self\b/i,
  /\bdon'?t want to (live|be here|wake up)\b/i,
  /\bwant to die\b/i,
  /\bbetter off (without me|dead)\b/i,
  /\boverdos(e|ing)\b/i,
  /\bno reason to (live|go on)\b/i,
  /\bplan(ning)? to (die|end it)\b/i,

  // Spanish
  /\bsuicid(io|arme|a|arse)\b/i,
  /\bquiero morir(me)?\b/i,
  /\bno quiero (vivir|seguir viviendo|estar aqu[ií]|despertar)\b/i,
  /\bmatarme\b/i,
  /\bquitarme la vida\b/i,
  /\bhacerme da[ñn]o\b/i,
  /\bautolesi[oó]n/i,
  /\bacabar con (todo|mi vida)\b/i,
  /\bsobredosis\b/i,
  /\bestar[ií]an mejor sin m[ií]\b/i,
  /\bno tengo (razones|motivos) para vivir\b/i,

  // Portuguese
  /\bsuic[ií]d(io|a|ar)\b/i,
  /\bquero morrer\b/i,
  /\bn[ãa]o quero (viver|mais viver|estar aqui|acordar)\b/i,
  /\bme matar\b/i,
  /\btirar (a )?minha vida\b/i,
  /\bme machucar\b/i,
  /\bautomutila/i,
  /\bacabar com (tudo|a minha vida|minha vida)\b/i,
  /\boverdose\b/i,
  /\bmelhor sem mim\b/i,
  /\bn[ãa]o aguento mais viver\b/i,

  // Chinese — simplified and traditional, no word boundaries
  /自杀|自殺/,
  /想死/,
  /不想活/,
  /活不下去/,
  /结束生命|結束生命/,
  /伤害自己|傷害自己/,
  /自残|自殘/,
  /没有活下去的理由|沒有活下去的理由/,
  /了结自己|了結自己/,

  // Arabic
  /انتحار|الانتحار|أنتحر|انتحر/,
  /أريد أن أموت|اريد ان اموت|أريد الموت|اريد الموت/,
  /لا أريد أن أعيش|لا اريد ان اعيش|لا أريد العيش|لا اريد العيش/,
  /إنهاء حياتي|انهاء حياتي/,
  /أؤذي نفسي|اؤذي نفسي|إيذاء النفس|ايذاء النفس/,
  /أفضل بدوني|افضل بدوني/,
  /لا أستطيع الاستمرار|لا استطيع الاستمرار/,
];

const ABUSE_PATTERNS: RegExp[] = [
  // English
  /\b(he|she|they) (hits|hit|beats|beat|hurts|hurt) me\b/i,
  /\bafraid to go home\b/i,
  /\bnot safe at home\b/i,
  /\bthreatened to (kill|hurt) me\b/i,

  // Spanish
  /\bme (pega|golpea|maltrata|lastima)\b/i,
  /\btengo miedo de (ir a casa|volver a casa)\b/i,
  /\bno estoy segur[oa] en (mi )?casa\b/i,
  /\bamenaz[óo] con (matarme|hacerme da[ñn]o)\b/i,

  // Portuguese
  /\bme (bate|agride|machuca|maltrata)\b/i,
  /\bmedo de (ir para casa|voltar para casa)\b/i,
  /\bn[ãa]o estou segur[oa] em casa\b/i,
  /\bamea[çc]ou me (matar|machucar)\b/i,

  // Chinese
  /打我|家暴/,
  /不敢回家/,
  /在家不安全/,
  /威胁要杀我|威脅要殺我/,

  // Arabic
  /يضربني|تضربني/,
  /أخاف الذهاب إلى البيت|اخاف الذهاب الى البيت/,
  /لست آمنا في المنزل|لست آمنة في المنزل/,
  /هددني بالقتل/,
];

const MEDICAL_PATTERNS: RegExp[] = [
  // English
  /\bchest pain\b/i,
  /\bcan'?t breathe\b/i,
  /\bstruggling to breathe\b/i,
  /\bshortness of breath\b/i,
  /\bpassing out\b/i,
  /\bfainted\b/i,
  /\bseizure\b/i,
  /\bconvulsion\b/i,
  /\bblue lips\b/i,
  /\bunresponsive\b/i,
  /\bvomiting blood\b/i,
  /\bcoughing up blood\b/i,
  /\bsevere bleeding\b/i,
  /\bnumbness on one side\b/i,
  /\bface is drooping\b/i,
  /\bslurred speech\b/i,

  // Spanish
  /\bdolor (en el|de) pecho\b/i,
  /\bno puedo respirar\b/i,
  /\bfalta de aire\b/i,
  /\bme voy a desmayar\b/i,
  /\bme desmay[ée]\b/i,
  /\bconvulsi[oó]n/i,
  /\bvomitando sangre\b/i,
  /\bsangrado (grave|abundante)\b/i,
  /\bhabla arrastrada\b/i,

  // Portuguese
  /\bdor no peito\b/i,
  /\bn[ãa]o consigo respirar\b/i,
  /\bfalta de ar\b/i,
  /\bvou desmaiar\b/i,
  /\bdesmaiei\b/i,
  /\bconvuls[ãa]o/i,
  /\bvomitando sangue\b/i,
  /\bsangramento (grave|intenso)\b/i,

  // Chinese
  /胸痛|胸口痛/,
  /无法呼吸|無法呼吸|不能呼吸/,
  /呼吸困难|呼吸困難/,
  /快要昏倒|昏过去|昏過去/,
  /癫痫|癲癇|抽搐/,
  /吐血|咳血/,
  /大出血/,

  // Arabic
  /ألم في الصدر|الم في الصدر/,
  /لا أستطيع التنفس|لا استطيع التنفس/,
  /ضيق في التنفس/,
  /سأغمى علي|سوف أغمى/,
  /تشنج|نوبة صرع/,
  /أتقيأ دما|اتقيا دما/,
  /نزيف حاد/,
];

const PANIC_PATTERNS: RegExp[] = [
  // English
  /\bpanic attack\b/i,
  /\b(i'?m|i am) panicking\b/i,
  /\bheart is racing\b/i,
  /\bchest feels tight\b/i,
  /\bfreaking out\b/i,
  /\bspiral(l)?ing\b/i,
  /\bhyperventilat/i,

  // Spanish
  /\bataque de p[áa]nico\b/i,
  /\bcrisis de ansiedad\b/i,
  /\bestoy en p[áa]nico\b/i,
  /\bel coraz[óo]n (me )?late muy r[áa]pido\b/i,
  /\bopresi[óo]n en el pecho\b/i,
  /\bhiperventil/i,

  // Portuguese
  /\bataque de p[âa]nico\b/i,
  /\bcrise de ansiedade\b/i,
  /\bestou em p[âa]nico\b/i,
  /\bcora[çc][ãa]o (est[áa] )?acelerado\b/i,
  /\baperto no peito\b/i,
  /\bhiperventil/i,

  // Chinese
  /恐慌发作|恐慌發作|惊恐发作|驚恐發作/,
  /心跳很快|心跳加速/,
  /胸口发闷|胸口發悶|胸闷|胸悶/,
  /过度换气|過度換氣/,

  // Arabic
  /نوبة هلع|نوبة ذعر/,
  /قلبي يدق بسرعة/,
  /ضيق في الصدر/,
  /فرط التنفس/,
];

export type SafetyLevel = "none" | "panic" | "medical" | "crisis";

export type SafetyScreen = {
  level: SafetyLevel;
  /** True when the app must show resources and skip AI interpretation. */
  blocksAi: boolean;
  matched: string[];
};

const matches = (text: string, patterns: RegExp[]) => patterns.some((p) => p.test(text));

/**
 * Highest severity wins. Crisis and medical both block AI interpretation —
 * someone describing chest pain needs an ambulance, not a reframe.
 */
export function screenText(text: string): SafetyScreen {
  const matched: string[] = [];
  if (matches(text, CRISIS_PATTERNS)) matched.push("crisis");
  if (matches(text, ABUSE_PATTERNS)) matched.push("safety-at-home");
  if (matches(text, MEDICAL_PATTERNS)) matched.push("medical");
  if (matches(text, PANIC_PATTERNS)) matched.push("panic");

  if (matched.includes("crisis") || matched.includes("safety-at-home")) {
    return { level: "crisis", blocksAi: true, matched };
  }
  if (matched.includes("medical")) return { level: "medical", blocksAi: true, matched };
  if (matched.includes("panic")) return { level: "panic", blocksAi: false, matched };
  return { level: "none", blocksAi: false, matched };
}

/* ------------------------------------------------------------- resources */

export type CrisisLine = { name: string; contact: string; note?: string; emergency?: boolean };
export type CrisisResources = {
  region: CrisisRegion;
  label: string;
  lines: CrisisLine[];
  /**
   * False until a human has confirmed every number in this region connects to
   * what it claims to. An unverified number is worse than no number: someone
   * dials it in the worst moment of their life and reaches a dead line.
   *
   * Regions that are not yet verified still get their emergency number — those
   * are stable and widely known — plus findahelpline.com, which is maintained
   * and checked by people whose job that is. That is a better answer than a
   * national line I am not certain about.
   */
  verified: boolean;
  /** When a human last checked. Staleness is a safety problem, so it is visible. */
  verifiedOn?: string;
};

/** Appended to every region, so there is always a maintained fallback. */
const FIND_A_HELPLINE: CrisisLine = {
  name: "Find a helpline",
  contact: "findahelpline.com",
  note: "Verified crisis lines in over 130 countries",
};

const RESOURCES: Record<CrisisRegion, CrisisResources> = {
  AU: {
    region: "AU",
    label: "Australia",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "000", note: "If you are in immediate danger", emergency: true },
      { name: "Lifeline", contact: "13 11 14", note: "24/7" },
      { name: "Beyond Blue", contact: "1300 22 4636", note: "24/7" },
      { name: "13YARN", contact: "13 92 76", note: "24/7, for Aboriginal and Torres Strait Islander people" },
      { name: "1800RESPECT", contact: "1800 737 732", note: "24/7, family and sexual violence" },
    ],
  },
  NZ: {
    region: "NZ",
    label: "New Zealand",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "111", emergency: true },
      { name: "Need to talk?", contact: "Call or text 1737", note: "Free, 24/7" },
      // Lifeline Aotearoa cut its overnight service in November 2025 over
      // funding. Saying 24/7 here would send someone to a line that does not
      // answer at 3am, which is exactly when they would call.
      { name: "Lifeline Aotearoa", contact: "0800 543 354", note: "7am–midnight" },
    ],
  },
  US: {
    region: "US",
    label: "United States",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "911", emergency: true },
      { name: "Suicide & Crisis Lifeline", contact: "988", note: "Call or text, 24/7" },
      { name: "Crisis Text Line", contact: "Text HOME to 741741", note: "24/7" },
    ],
  },
  CA: {
    region: "CA",
    label: "Canada",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "911", emergency: true },
      // Talk Suicide Canada (1-833-456-4566) was folded into 988 and its own
      // site now redirects there. It used to be listed here.
      { name: "Suicide Crisis Helpline", contact: "988", note: "Call or text, 24/7" },
    ],
  },
  UK: {
    region: "UK",
    label: "United Kingdom",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "999", emergency: true },
      { name: "Samaritans", contact: "116 123", note: "Free, 24/7" },
      { name: "Shout", contact: "Text SHOUT to 85258", note: "24/7" },
    ],
  },
  IE: {
    region: "IE",
    label: "Ireland",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "112 or 999", emergency: true },
      { name: "Samaritans", contact: "116 123", note: "Free, 24/7" },
      { name: "Text About It", contact: "Text HELLO to 50808", note: "Free, 24/7" },
    ],
  },

  /* --- Spanish-speaking ------------------------------------------------- */
  ES: {
    region: "ES",
    label: "España",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergencias", contact: "112", emergency: true },
      { name: "Línea 024", contact: "024", note: "Conducta suicida. Gratuita, 24 h" },
      { name: "Teléfono de la Esperanza", contact: "717 003 717", note: "Gratuito, 24 h" },
    ],
  },
  MX: {
    region: "MX",
    label: "México",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergencias", contact: "911", emergency: true },
      { name: "Línea de la Vida", contact: "800 911 2000", note: "Gratuita, 24 h" },
    ],
  },
  AR: {
    region: "AR",
    label: "Argentina",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergencias", contact: "911", emergency: true },
      {
        name: "Línea Nacional de Urgencia en Salud Mental",
        contact: "0800 999 0091",
        note: "Gratuita, 24 h",
      },
    ],
  },
  CO: {
    region: "CO",
    label: "Colombia",
    // Checked and deliberately left with the emergency number only. Línea 106
    // is implemented department by department and simply does not exist in
    // several of them, and 192 opción 4 could not be confirmed as current.
    // A national-looking number that is dead in Amazonas is worse than none.
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [{ name: "Emergencias", contact: "123", emergency: true }],
  },
  CL: {
    region: "CL",
    label: "Chile",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      // Chile has no single emergency number. 131 is the ambulance, and
      // listing it alone as "emergencias" sends someone in danger from another
      // person to the wrong service.
      { name: "Ambulancia (SAMU)", contact: "131", emergency: true },
      { name: "Carabineros", contact: "133", emergency: true },
      { name: "Línea *4141", contact: "*4141", note: "Prevención del suicidio. Gratuita, 24 h" },
      { name: "Salud Responde", contact: "600 360 7777", note: "24 h, costo de llamada local" },
    ],
  },

  /* --- Portuguese-speaking ---------------------------------------------- */
  BR: {
    region: "BR",
    label: "Brasil",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "SAMU", contact: "192", note: "Emergência médica", emergency: true },
      { name: "Polícia Militar", contact: "190", note: "Perigo imediato", emergency: true },
      { name: "CVV", contact: "188", note: "Apoio emocional. Gratuito, 24 h" },
    ],
  },
  PT: {
    region: "PT",
    label: "Portugal",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergência", contact: "112", emergency: true },
      {
        name: "Linha Nacional de Prevenção do Suicídio",
        contact: "1411",
        note: "Gratuita, 24 h",
      },
      { name: "SNS 24", contact: "808 24 24 24", note: "24 h, custo de chamada local" },
    ],
  },

  /* --- Chinese-speaking -------------------------------------------------- */
  TW: {
    region: "TW",
    label: "台灣",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "緊急電話", contact: "119", emergency: true },
      { name: "安心專線", contact: "1925", note: "衛生福利部，24 小時" },
      { name: "生命線", contact: "1995", note: "24 小時" },
    ],
  },
  HK: {
    region: "HK",
    label: "香港",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "緊急電話", contact: "999", emergency: true },
      // These are two different charities and the numbers were previously
      // crossed here: 2896 0000 belongs to 香港撒瑪利亞會, not to the
      // Befrienders. Someone would have reached a real line under the wrong
      // name, which is the kind of error that survives because it looks fine.
      { name: "香港撒瑪利亞防止自殺會", contact: "2389 2222", note: "24 小時" },
      { name: "香港撒瑪利亞會", contact: "2896 0000", note: "24 小時，多語言" },
    ],
  },
  SG: {
    region: "SG",
    label: "Singapore",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "Emergency", contact: "995", emergency: true },
      { name: "Samaritans of Singapore", contact: "1767", note: "24 hours" },
      { name: "National Mindline", contact: "1771", note: "24 hours" },
    ],
  },

  /* --- Arabic-speaking --------------------------------------------------- */
  AE: {
    region: "AE",
    label: "الإمارات",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "الشرطة", contact: "999", emergency: true },
      { name: "الإسعاف", contact: "998", emergency: true },
      { name: "خط الدعم النفسي", contact: "800 4673", note: "٨ ص - ٨ م" },
    ],
  },
  SA: {
    region: "SA",
    label: "السعودية",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      // The emergency number genuinely differs by region here. Showing 997
      // alone, as this file used to, is no help at all to someone who needs
      // police rather than an ambulance.
      { name: "الطوارئ الموحد", contact: "911", note: "الرياض ومكة والمدينة والشرقية", emergency: true },
      { name: "الشرطة", contact: "999", note: "بقية المناطق", emergency: true },
      { name: "الهلال الأحمر", contact: "997", note: "إسعاف" },
      { name: "مركز الاستشارات النفسية", contact: "920033360", note: "٨ ص - ٨ م" },
    ],
  },
  EG: {
    region: "EG",
    label: "مصر",
    // Emergency numbers only, on purpose. The national mental-health line has
    // a documented history of going out of service without notice, and the
    // number that replaced it is months old with no track record.
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [
      { name: "الإسعاف", contact: "123", emergency: true },
      { name: "الشرطة", contact: "122", emergency: true },
    ],
  },

  INTL: {
    region: "INTL",
    label: "International",
    verified: true,
    verifiedOn: "2026-09-13",
    lines: [{ name: "Emergency", contact: "Your local emergency number", emergency: true }],
  },
};

export const ALL_REGIONS: CrisisRegion[] = [
  "AU", "NZ", "US", "CA", "UK", "IE",
  "ES", "MX", "AR", "CO", "CL",
  "BR", "PT",
  "TW", "HK", "SG",
  "AE", "SA", "EG",
  "INTL",
];

export function crisisResources(region: CrisisRegion = "AU"): CrisisResources {
  const found = RESOURCES[region] ?? RESOURCES.INTL;
  // findahelpline is always last and always present. It is maintained by
  // people who check these numbers, which is more than this file can claim.
  return { ...found, lines: [...found.lines, FIND_A_HELPLINE] };
}

export function regionLabel(region: CrisisRegion): string {
  return (RESOURCES[region] ?? RESOURCES.INTL).label;
}

/** Regions whose numbers a human still has to confirm before launch. */
export function unverifiedRegions(): CrisisRegion[] {
  return ALL_REGIONS.filter((region) => !RESOURCES[region]?.verified);
}

/**
 * Best-effort region from the browser's IANA timezone, so the right numbers
 * show without asking. Deliberately conservative: anything unrecognised falls
 * through to the international list rather than guessing at an emergency
 * number that would not connect.
 */
export function regionFromTimeZone(timeZone: string | undefined | null): CrisisRegion {
  if (!timeZone) return "INTL";
  const zone = timeZone.toLowerCase();

  if (zone.startsWith("australia/") || zone === "antarctica/macquarie") return "AU";
  if (zone === "pacific/auckland" || zone === "pacific/chatham") return "NZ";
  if (zone === "europe/london" || zone === "europe/belfast") return "UK";
  if (zone === "europe/dublin") return "IE";
  if (zone === "europe/madrid" || zone === "africa/ceuta" || zone === "atlantic/canary") return "ES";
  if (zone === "europe/lisbon" || zone === "atlantic/madeira" || zone === "atlantic/azores") return "PT";
  if (zone === "asia/taipei") return "TW";
  if (zone === "asia/hong_kong") return "HK";
  if (zone === "asia/singapore") return "SG";
  if (zone === "asia/dubai") return "AE";
  if (zone === "asia/riyadh") return "SA";
  if (zone === "africa/cairo") return "EG";

  if (zone.startsWith("america/argentina/") || zone === "america/buenos_aires") return "AR";
  if (zone === "america/santiago" || zone === "pacific/easter") return "CL";
  if (zone === "america/bogota") return "CO";

  const MEXICO = [
    "america/mexico_city", "america/tijuana", "america/monterrey", "america/cancun",
    "america/chihuahua", "america/hermosillo", "america/mazatlan", "america/merida",
  ];
  if (MEXICO.includes(zone)) return "MX";

  const BRAZIL = [
    "america/sao_paulo", "america/bahia", "america/fortaleza", "america/recife",
    "america/manaus", "america/belem", "america/cuiaba", "america/campo_grande",
    "america/porto_velho", "america/boa_vista", "america/rio_branco", "america/maceio",
    "america/araguaina", "america/santarem", "america/noronha",
  ];
  if (BRAZIL.includes(zone)) return "BR";

  const CANADA = [
    "america/toronto", "america/vancouver", "america/edmonton", "america/winnipeg",
    "america/halifax", "america/st_johns", "america/regina", "america/moncton",
    "america/whitehorse", "america/yellowknife", "america/iqaluit",
  ];
  if (CANADA.includes(zone)) return "CA";

  if (zone.startsWith("america/") || zone.startsWith("us/") || zone === "pacific/honolulu") {
    return "US";
  }
  return "INTL";
}

export const NON_CLINICAL_DISCLAIMER =
  "Mentara is a self-guided wellbeing tool. It is not therapy, not a clinician, and it cannot diagnose or treat anything. If something feels beyond what a tool should hold, please involve a real person.";
