import Link from "next/link";
import type { Metadata } from "next";
import { NON_CLINICAL_DISCLAIMER } from "@/lib/safety";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return (
    <main id="main" className="stack py-12">
      <Link href="/" className="text-sm text-muted underline underline-offset-4 hover:text-ink">
        Mentara
      </Link>

      <h1 className="mt-6 font-serif text-3xl text-ink">Terms</h1>

      <div className="mt-8 space-y-8">
        <section>
          <h2 className="font-serif text-xl text-ink">What Mentara is</h2>
          <p className="mt-2.5 leading-relaxed text-muted">{NON_CLINICAL_DISCLAIMER}</p>
          <p className="mt-2.5 leading-relaxed text-muted">
            It is a self-guided wellbeing tool: breathing and grounding exercises, a private
            journal, daily self-ratings, and summaries of your own entries. It does not assess,
            diagnose, or treat any condition, and it is not a substitute for care from a qualified
            professional.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">In an emergency</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            Mentara is not monitored. Nobody is reading what you write, and nothing here reaches a
            human unless you fill in the Find help form yourself — and even then, a practitioner
            reads that form, not your journal, and not in a hurry. It is not a way to get help
            tonight. If you are in danger or thinking about harming yourself, contact emergency
            services or a crisis line — the app lists numbers for your region on the{" "}
            <Link href="/sos" className="underline underline-offset-4">
              support page
            </Link>{" "}
            and in settings.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">AI-generated content</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            If you enable reflections, some text is generated by a language model. It can be wrong,
            it can miss the point, and it has no knowledge of you beyond what you typed. Treat it as
            a prompt for your own thinking, not as an assessment.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">Your account</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            You are responsible for keeping your password to yourself. You can export or delete
            everything at any time from settings. Accounts are for people aged 16 and over.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">Paid plans</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            Mentara is usable without paying. The SOS flow, the tools, check-ins and journalling
            are on the free plan, and crisis resources are never behind a payment of any kind.
            Pro and Premium raise the monthly limits and unlock a few extra features.
          </p>
          <p className="mt-2.5 leading-relaxed text-muted">
            Subscriptions renew each month until cancelled. On iPhone or iPad, billing and
            cancellation are handled by Apple in your device settings; on the web they are handled
            by our payment provider, and you can cancel from the link on your receipt or by
            emailing us. Cancelling stops the next renewal — you keep what you have paid for until
            the end of the period you are in.
          </p>
          <p className="mt-2.5 leading-relaxed text-muted">
            If a payment fails, we do not cut off access while the retry is still running. Prices
            can change, but not for a period you have already paid for, and we will tell you
            before a change takes effect. Nothing here limits your rights under Australian
            Consumer Law, including a refund where those rights apply.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">Being matched with a practitioner</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            Mentara is an introduction service. When you ask to be matched, registered practitioners
            who fit what you asked for can offer to take you on, and you choose one or none of
            them. That is where Mentara&rsquo;s part ends. The care itself is between you and that
            practitioner, on their terms, under their registration and their insurance. Mentara does
            not provide it, supervise it, or see it.
          </p>
          <p className="mt-2.5 leading-relaxed text-muted">
            Practitioners are listed only after a person has checked their registration on the
            public register, and are removed when that registration lapses. That check is a check of
            the register on a date — it is not a recommendation, an endorsement, or an opinion about
            whether someone is right for you. Nobody pays to rank higher, and no fee is taken from
            what you pay them.
          </p>
          <p className="mt-2.5 leading-relaxed text-muted">
            There is no guarantee anyone will offer, or that an offer will arrive quickly. Nothing
            is charged to you for an introduction.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">If you are a practitioner</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            A listing costs $30 per month and renews until you cancel. You can cancel at any time
            and keep the listing until the end of the period you have paid for. Paying does not buy
            referrals, placement, or a number of them — it buys a listing, and some months there
            will be nothing worth taking.
          </p>
          <p className="mt-2.5 leading-relaxed text-muted">
            You are responsible for your own registration and insurance, for telling us when either
            changes, and for keeping your listing true. Listings cannot claim outcomes, success
            rates, or carry testimonials: section 133 of the National Law does not allow them for a
            regulated health service, and that is on you as much as on us. Lapsed registration, or a
            listing we cannot verify, ends the listing.
          </p>
          <p className="mt-2.5 leading-relaxed text-muted">
            What you receive about a person is what they wrote on the form, and once they choose
            you, their name and email. From that point they are your client and their information is
            yours to handle under the law that applies to you.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">No warranty</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            The service is provided as it is, without guarantees of availability or of any
            particular outcome. To the extent the law allows, liability for loss arising from use
            of the app is excluded — except for rights that cannot be excluded under Australian
            Consumer Law.
          </p>
        </section>
      </div>

      <p className="mt-10 border-t border-line pt-6 text-sm text-faint">
        These terms are a starting point written for a product at this stage. Have a lawyer review
        them before you take payment or launch publicly — in particular the practitioner sections,
        and the written agreement that has to sit behind them covering how a person&rsquo;s
        information is handled once it reaches a practitioner.
      </p>
    </main>
  );
}
