import Link from "next/link";
import type { Metadata } from "next";
import { NON_CLINICAL_DISCLAIMER } from "@/lib/safety";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return (
    <main id="main" className="stack py-12">
      <Link href="/" className="text-sm text-muted underline underline-offset-4 hover:text-ink">
        Mentara
      </Link>

      <h1 className="mt-6 font-serif text-3xl text-ink">Terms</h1>

      <div className="mt-8 space-y-8">
        <section>
          <h2 className="font-serif text-xl text-ink">What Mentara is</h2>
          <p className="mt-2.5 leading-relaxed text-muted">{NON_CLINICAL_DISCLAIMER}</p>
          <p className="mt-2.5 leading-relaxed text-muted">
            It is a self-guided wellbeing tool: breathing and grounding exercises, a private
            journal, daily self-ratings, and summaries of your own entries. It does not assess,
            diagnose, or treat any condition, and it is not a substitute for care from a qualified
            professional.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">In an emergency</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            Mentara is not monitored. Nobody is reading what you write, and nothing here reaches a
            human. If you are in danger or thinking about harming yourself, contact emergency
            services or a crisis line — the app lists numbers for your region on the{" "}
            <Link href="/sos" className="underline underline-offset-4">
              support page
            </Link>{" "}
            and in settings.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">AI-generated content</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            If you enable reflections, some text is generated by a language model. It can be wrong,
            it can miss the point, and it has no knowledge of you beyond what you typed. Treat it as
            a prompt for your own thinking, not as an assessment.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">Your account</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            You are responsible for keeping your password to yourself. You can export or delete
            everything at any time from settings. Accounts are for people aged 16 and over.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl text-ink">No warranty</h2>
          <p className="mt-2.5 leading-relaxed text-muted">
            The service is provided as it is, without guarantees of availability or of any
            particular outcome. To the extent the law allows, liability for loss arising from use
            of the app is excluded — except for rights that cannot be excluded under Australian
            Consumer Law.
          </p>
        </section>
      </div>

      <p className="mt-10 border-t border-line pt-6 text-sm text-faint">
        These terms are a starting point written for a product at this stage. Have a lawyer review
        them before you take payment or launch publicly.
      </p>
    </main>
  );
}
