import { LegalPage, LegalSection } from "@/components/legal-page";

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy Policy"
      title="How we collect, use, and protect your information"
      description="This policy explains what information Mentara collects, how it is used to power support, insights, and personalization, and the choices users have around their data."
      lastUpdated="15 March 2026"
    >
      <LegalSection title="What we collect">
        <p>
          We may collect account information such as your email address, along with information you choose to enter into the
          product, including mood check-ins, journaling entries, support conversations, SOS check-ins, onboarding answers,
          sleep-related logs, anxiety logs, and feature feedback.
        </p>
        <p>
          We also collect limited technical information needed to run the service, such as browser metadata, basic usage
          information, and service logs generated by our infrastructure providers.
        </p>
      </LegalSection>

      <LegalSection title="How we use your information">
        <p>We use your information to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>create and secure your account</li>
          <li>provide support conversations, journaling, SOS tools, and personalized insights</li>
          <li>generate pattern recognition features such as mirror insights, thinking profiles, and AI Twin responses</li>
          <li>improve product safety, reliability, and user experience</li>
          <li>respond to support requests and service issues</li>
        </ul>
      </LegalSection>

      <LegalSection title="Sensitive information">
        <p>
          Because this product is designed around mental health support, some of the information you enter may be sensitive.
          We treat journaling entries, mood data, support conversations, and related behavioral data as sensitive personal
          information and only use it to operate, personalize, and improve the service.
        </p>
      </LegalSection>

      <LegalSection title="Third-party services">
        <p>We use third-party providers to operate the product. These may include:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Supabase for authentication and database storage</li>
          <li>Vercel for hosting and delivery</li>
          <li>OpenAI for AI-generated responses and analysis</li>
        </ul>
        <p>
          These providers may process data on our behalf so the app can function. We do not sell your personal information.
        </p>
      </LegalSection>

      <LegalSection title="Data retention and deletion">
        <p>
          We keep account and product data for as long as reasonably necessary to provide the service, comply with legal
          obligations, resolve disputes, and protect the integrity of the platform.
        </p>
        <p>
          If you want your account data deleted, contact us using the details listed below. We will handle deletion requests in
          line with applicable law and our operational requirements.
        </p>
      </LegalSection>

      <LegalSection title="Security">
        <p>
          We take reasonable steps to protect user information, but no system can guarantee absolute security. Users should
          avoid sharing highly sensitive information unless they are comfortable storing it in a digital support product.
        </p>
      </LegalSection>

      <LegalSection title="Your choices">
        <p>You may choose not to provide certain information, but some features may not work without it.</p>
        <p>
          Depending on where you live, you may have rights to access, correct, or request deletion of your personal information.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          For privacy questions or data requests, contact: <a className="text-pine underline" href="mailto:info@bozahealthgroup.com">info@bozahealthgroup.com</a>
        </p>
      </LegalSection>
    </LegalPage>
  );
}
