import { LegalPage, LegalSection } from "@/components/legal-page";

export default function DisclaimerPage() {
  return (
    <LegalPage
      eyebrow="Service Disclaimer"
      title="Important limits of this product"
      description="Mentara is designed to offer emotional support, reflection, and pattern awareness. It should not be understood as clinical care or emergency intervention."
      lastUpdated="15 March 2026"
    >
      <LegalSection title="Not therapy or medical care">
        <p>
          Mentara is not a licensed therapist, psychologist, psychiatrist, doctor, or crisis service. It is not a
          substitute for professional mental health treatment or medical advice.
        </p>
      </LegalSection>

      <LegalSection title="Not for emergencies">
        <p>
          If you are in immediate danger, believe you may harm yourself or someone else, or need urgent crisis support, contact
          your local emergency services or a crisis hotline immediately.
        </p>
      </LegalSection>

      <LegalSection title="AI-generated content">
        <p>
          Some responses are generated by AI systems using the information you provide. AI-generated content may be incomplete,
          imperfect, or inappropriate for your situation. You should use judgment and seek professional help when needed.
        </p>
      </LegalSection>

      <LegalSection title="Use with care">
        <p>
          This product is intended for support, reflection, and self-observation. It should be used carefully, especially when
          decisions carry medical, legal, financial, or safety consequences.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
